[platformio]
src_dir = firmware/TFT_Graphing_Calculator

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
  prenticedavid/MCUFRIEND_kbv
  adafruit/Adafruit GFX Library
  adafruit/TouchScreen
monitor_speed = 9600
